py_test(
    name = "script_unit_test",
    main = "script_unit_test.py",
    data = [],
    args = [],
    deps = [
        "//script",
    ],
    srcs = [
        "script_unit_test.py",
    ] + glob(["script/**/*.py"]),
)

